on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Deploy
jobs:
  production:
    name: Upload Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa_rishsftp
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        run: rsync -ahvz -e "ssh -i ~/.ssh/id_rsa_rishsftp -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html/rish/wp/