name: Develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Upload Develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: rish_ida_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Develop
        run: rsync –rsync-path="sudo rsync" -rlOcv --omit-dir-times --exclude ".git/" --exclude ".github/" -e "ssh -o 'PubkeyAcceptedKeyTypes +ssh-rsa' -i ~/.ssh/rish_ida_rsa -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html/dev/rish/wp/
